export const RECEIVE_FILMS='RECEIVE_FILMS';
export const RECEIVE_STATUS="RECEIVE_STATUS";
export const RECEIVE_CINEMA="RECEIVE_CINEMA";
export const AUTH_LOGIN="AUTH_LOGIN";
export const LOGIN_PRIVITE_INIT="LOGIN_PRIVITE_INIT";
export const LOGIN_PRIVITE_GET="LOGIN_PRIVITE_GET";
export const LOGIN_PRIVITE_SKIP="LOGIN_PRIVITE_SKIP";

